//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.ServiceClient
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EchoRequest", Namespace="http://schemas.datacontract.org/2004/07/USI.Contracts.DataContracts.School")]
    public partial class EchoRequest : object
    {
        
        private string OrgCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgCode
        {
            get
            {
                return this.OrgCodeField;
            }
            set
            {
                this.OrgCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EchoResponse", Namespace="http://schemas.datacontract.org/2004/07/USI.Contracts.DataContracts.School")]
    public partial class EchoResponse : object
    {
        
        private System.Collections.Generic.List<string> DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorInfo", Namespace="http://usi.gov.au/2018/ws")]
    public partial class ErrorInfo : object
    {
        
        private int CodeField;
        
        private string TitleField;
        
        private string MessageField;
        
        private System.Collections.Generic.List<string> MemberNamesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.List<string> MemberNames
        {
            get
            {
                return this.MemberNamesField;
            }
            set
            {
                this.MemberNamesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuzzySearchRequest", Namespace="http://schemas.datacontract.org/2004/07/USI.Contracts.DataContracts.School")]
    public partial class FuzzySearchRequest : object
    {
        
        private string CountryOfBirthCodeField;
        
        private System.DateTime DateOfBirthField;
        
        private string FamilyNameField;
        
        private string FirstNameField;
        
        private string GenderCodeField;
        
        private string MiddleNameField;
        
        private string OrgCodeField;
        
        private string SingleNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryOfBirthCode
        {
            get
            {
                return this.CountryOfBirthCodeField;
            }
            set
            {
                this.CountryOfBirthCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FamilyName
        {
            get
            {
                return this.FamilyNameField;
            }
            set
            {
                this.FamilyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenderCode
        {
            get
            {
                return this.GenderCodeField;
            }
            set
            {
                this.GenderCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgCode
        {
            get
            {
                return this.OrgCodeField;
            }
            set
            {
                this.OrgCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SingleName
        {
            get
            {
                return this.SingleNameField;
            }
            set
            {
                this.SingleNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuzzySearchResponse", Namespace="http://schemas.datacontract.org/2004/07/USI.Contracts.DataContracts.School")]
    public partial class FuzzySearchResponse : object
    {
        
        private Common.ServiceClient.FuzzySearchResult ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Common.ServiceClient.FuzzySearchResult Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuzzySearchResult", Namespace="http://schemas.datacontract.org/2004/07/USI.Contracts.DataContracts.School")]
    public enum FuzzySearchResult : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Match = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoMatch = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://usi.gov.au/2024/school/ws", ConfigurationName="Common.ServiceClient.IUsiService")]
    public interface IUsiService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usi.gov.au/2024/school/ws/Echo", ReplyAction="http://usi.gov.au/2024/school/ws/EchoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Common.ServiceClient.ErrorInfo), Action="http://usi.gov.au/2024/school/ws/EchoResponseErrorInfoFault", Name="ErrorInfo", Namespace="http://usi.gov.au/2018/ws")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Collections.Generic.List<Common.ServiceClient.ErrorInfo>), Action="http://usi.gov.au/2024/school/ws/EchoResponseErrorInfoFault", Name="ArrayOfErrorInfo", Namespace="http://usi.gov.au/2018/ws")]
        System.Threading.Tasks.Task<Common.ServiceClient.EchoResponse> EchoAsync(Common.ServiceClient.EchoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usi.gov.au/2024/school/ws/FuzzySearch", ReplyAction="http://usi.gov.au/2024/school/ws/FuzzySearchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Common.ServiceClient.ErrorInfo), Action="http://usi.gov.au/2024/school/ws/FuzzySearchResponseErrorInfoFault", Name="ErrorInfo", Namespace="http://usi.gov.au/2018/ws")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Collections.Generic.List<Common.ServiceClient.ErrorInfo>), Action="http://usi.gov.au/2024/school/ws/FuzzySearchResponseErrorInfoFault", Name="ArrayOfErrorInfo", Namespace="http://usi.gov.au/2018/ws")]
        System.Threading.Tasks.Task<Common.ServiceClient.FuzzySearchResponse> FuzzyAsync(Common.ServiceClient.FuzzySearchRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IUsiServiceChannel : Common.ServiceClient.IUsiService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class UsiServiceClient : System.ServiceModel.ClientBase<Common.ServiceClient.IUsiService>, Common.ServiceClient.IUsiService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UsiServiceClient() : 
                base(UsiServiceClient.GetDefaultBinding(), UsiServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WS2007FederationHttpBinding_IUsiService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsiServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UsiServiceClient.GetBindingForEndpoint(endpointConfiguration), UsiServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsiServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UsiServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsiServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UsiServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Common.ServiceClient.EchoResponse> EchoAsync(Common.ServiceClient.EchoRequest request)
        {
            return base.Channel.EchoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Common.ServiceClient.FuzzySearchResponse> FuzzyAsync(Common.ServiceClient.FuzzySearchRequest request)
        {
            return base.Channel.FuzzyAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS2007FederationHttpBinding_IUsiService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TransportSecurityBindingElement userNameOverTransportSecurityBindingElement = System.ServiceModel.Channels.SecurityBindingElement.CreateUserNameOverTransportBindingElement();
                userNameOverTransportSecurityBindingElement.MessageSecurityVersion = System.ServiceModel.MessageSecurityVersion.WSSecurity11WSTrust13WSSecureConversation13WSSecurityPolicy12BasicSecurityProfile10;
                result.Elements.Add(userNameOverTransportSecurityBindingElement);
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS2007FederationHttpBinding_IUsiService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:4443/Service/School/UsiService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UsiServiceClient.GetBindingForEndpoint(EndpointConfiguration.WS2007FederationHttpBinding_IUsiService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UsiServiceClient.GetEndpointAddress(EndpointConfiguration.WS2007FederationHttpBinding_IUsiService);
        }
        
        public enum EndpointConfiguration
        {
            
            WS2007FederationHttpBinding_IUsiService,
        }
    }
}
